#environment.yml
name: wireworm-transcriptomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core bioinformatics tools
  - fastqc=0.12.1
  - multiqc=1.22.1
  - fastp=0.23.4
  - seqkit=2.10.0
  - trinity=2.15.2
  - cd-hit=4.8.1
  - busco=5.8.3
  - quast=5.0.2
  - blast=2.16.0
  - fcs-adaptor=0.5.5
  - tbl2asn=25.8
  - salmon=1.10.3
  - transdecoder=5.7.1
  - eggnog-mapper=2.1.12
  
  # Python environment for analysis
  - python=3.12
  - snakemake=7.32.4
  - goatools=1.3.5
  
  # Python packages for data handling and visualization
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyterlab